export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_FILTERED_PRODUCTS = "FETCH_FILTERED_PRODUCTS";
export const FETCH_CURRENCIES = "FETCH_CURRENCIES";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_QTY = "INCREMENT_QTY";
export const DECREMENT_QTY = "DECREMENT_QTY";

export const TOGGLE_CART_OVERLAY = "TOGGLE_CART_OVERLAY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";




