export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_CURRENT_CATEGORY_NAME = "FETCH_CURRENT_CATEGORY_NAME";

export const FETCH_CURRENCIES = "FETCH_CURRENCIES";
export const CHANGE_CURRENCY_SYMBOL = "CHANGE_CURRENCY_SYMBOL";
export const TOGGLE_CART_OVERLAY = "TOGGLE_CART_OVERLAY";
export const CLOSE_CART_OVERLAY = "CLOSE_CART_OVERLAY";

export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const CHANGE_PRODUCT_ATTRIBUTE = "CHANGE_PRODUCT_ATTRIBUTE";
export const CHANGE_PRODUCT_ATTRIBUTE_IN_CART =
  "CHANGE_PRODUCT_ATTRIBUTE_IN_CART";

export const CHANGE_PRODUCT_QUANITY = "CHANGE_PRODUCT_QUANITY";
